services:
  - type: web
    name: moncv
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: SERVER_NAME
        value: MYMEDAGA.onrener.com
      - key: DEBUG
        value: 'False'
      - key: DATABASE_URL
        fromDatabase:
          name: moncvdb
          property: connectionString

databases:
  - name: moncvdb
    databaseName: moncv
    user: moncv_user
    plan: free
