services:
  - type: web
    name: moncv
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SETTINGS_MODULE
        value: moncv.settings_dev
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: your-render-app-url.onrender.com
      - key: DEBUG
        value: 'False'
      - key: DATABASE_URL
        fromDatabase:
          name: moncvdb
          property: connectionString

databases:
  - name: moncvdb
    databaseName: moncv
    user: moncv_user
    plan: free
